[package]
name = "server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "server"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
protocol = { workspace = true }
movement = { workspace = true }
sensors = { workspace = true }
transport = { workspace = true }
viz = { workspace = true }
perception = { workspace = true }
map = { workspace = true }
map-opendrive = { workspace = true }

bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
glam = { workspace = true }
